title: PELUX
email: contact@pelux.io
description: PELUX is an agnostic automotive reference integration platform.
copyright: Copyright &copy; Luxoft Sweden AB 2018
license: Licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>
repo: <a href="https://github.com/pelagicore/pelux.io">Source</a> of this website
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pelux.io
twitter_username: luxoft
github_username:  pelagicore

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Jenkinsfile
  - Dockerfile
  - README.md
collections:
  download:
    output: true
